<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@820.vd1a_6cc65ef33">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@2692.v76b_089ccd026">
    <parentIds>
      <string>16</string>
    </parentIds>
    <id>17</id>
    <startId>13</startId>
  </node>
  <actions>
    <wf.a.TimingAction plugin="workflow-api@1153.vb_912c0e47fb_a_">
      <startTime>1653057047254</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@1153.vb_912c0e47fb_a_">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 1</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:664)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:610)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:554)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions class="empty-list"/>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>